import { ago, ahead } from '../domain/time'
import type { State } from '../domain/types'

export const STATE_VERSION = 2

const chat = (label: string, excerpt?: string, days = 1) => ({
  sourceId: 'src_claude',
  label,
  excerpt,
  at: ago(days),
})

export function createSeed(): State {
  return {
    version: STATE_VERSION,
    demo: { costReportImported: false },
    settings: { autoAccept: false, wakeIdeas: true, followUps: true, dailyReviewAt: '21:00' },

    projects: [
      {
        id: 'p_pcas',
        name: 'PCAS 重写',
        goal: '以个人长期记忆为核心的 AI 工作系统',
        status: 'active',
        progress:
          '需求简版 0.3 已定稿，旧代码已归档到 legacy 分支。正在做交互原型，后端数据模型待设计。',
        nextSteps: ['确定部署形态', '设计数据模型', '用原型走通典型场景'],
        updatedAt: ago(0.1),
      },
      {
        id: 'p_yufolo',
        name: 'Yufolo 运营',
        goal: '实时转录与翻译服务稳定运营',
        status: 'active',
        progress: '区域边缘节点已上线，伦敦链路延迟仍在观察。',
        nextSteps: ['复查伦敦边缘节点延迟', '跟进 Speechmatics 初创计划续期'],
        updatedAt: ago(1),
      },
      {
        id: 'p_model',
        name: '个人小模型',
        goal: '用积累的对话和纠正记录后训练一个个人小模型',
        status: 'paused',
        progress: '因推理和训练成本暂停，等待成本数据。',
        nextSteps: ['拿到本地推理的实际成本'],
        updatedAt: ago(21),
      },
    ],

    tasks: [
      {
        id: 't_model',
        title: '设计 PCAS 数据模型',
        notes: '原始资料层、事项层、记忆层、派生层；派生数据要记录来源和版本。',
        status: 'doing',
        projectId: 'p_pcas',
        due: ahead(3, 18),
        dependsOn: ['t_deploy'],
        triggers: [],
        sources: [chat('与 Claude 讨论 PCAS 重写', '数据模型要最先定，它决定了其他一切。')],
        history: [{ at: ago(0.2), by: 'user', summary: '开始处理' }],
        createdAt: ago(0.5),
        updatedAt: ago(0.2),
      },
      {
        id: 't_deploy',
        title: '确定 PCAS 部署形态',
        notes: '和 Yufolo 同一台服务器，还是本地优先？影响同步和授权设计。',
        status: 'todo',
        projectId: 'p_pcas',
        due: ahead(1, 12),
        dependsOn: [],
        triggers: [
          {
            id: 'tr_deploy',
            kind: 'time',
            description: '明天 10:00 提醒',
            nextAt: ahead(1, 10),
            active: true,
          },
        ],
        sources: [chat('与 Claude 讨论 PCAS 重写', '部署形态倾向哪种？')],
        history: [{ at: ago(0.3), by: 'ai', summary: '从对话中提取，已由你采纳' }],
        createdAt: ago(0.3),
        updatedAt: ago(0.3),
      },
      {
        id: 't_speechmatics',
        title: '跟进 Speechmatics 初创计划续期',
        status: 'waiting',
        projectId: 'p_yufolo',
        waitingFor: 'Speechmatics 商务回复',
        dependsOn: [],
        triggers: [
          {
            id: 'tr_sm',
            kind: 'event+delay',
            description: '发出续期邮件 3 天后',
            guard: '执行前核对：如已收到回复，自动撤销提醒',
            nextAt: ahead(2, 9),
            active: true,
          },
        ],
        sources: [
          {
            sourceId: 'src_email',
            label: '邮件：Startup Program renewal',
            excerpt: 'We will get back to you within a few business days.',
            at: ago(1),
          },
        ],
        history: [
          { at: ago(1), by: 'import', summary: '从邮件导入' },
          { at: ago(1), by: 'user', summary: '状态改为等待' },
        ],
        createdAt: ago(1),
        updatedAt: ago(1),
      },
      {
        id: 't_wechat',
        title: '验证微信聊天记录导出方式',
        notes: '官方没有接口，需要比较几种导出工具的格式和完整度。',
        status: 'todo',
        projectId: 'p_pcas',
        scheduled: ahead(2, 14),
        dependsOn: [],
        triggers: [],
        sources: [],
        history: [{ at: ago(0.3), by: 'user', summary: '创建' }],
        createdAt: ago(0.3),
        updatedAt: ago(0.3),
      },
      {
        id: 't_edge',
        title: '复查伦敦边缘节点延迟',
        status: 'todo',
        projectId: 'p_yufolo',
        scheduled: ahead(0, 16),
        dependsOn: [],
        triggers: [
          {
            id: 'tr_edge',
            kind: 'time',
            description: '每周一 09:00 复查',
            nextAt: ahead(6, 9),
            active: true,
          },
        ],
        sources: [],
        history: [{ at: ago(7), by: 'user', summary: '创建周期任务' }],
        createdAt: ago(7),
        updatedAt: ago(7),
      },
      {
        id: 't_import',
        title: '导入 Claude 和 ChatGPT 的历史对话',
        status: 'todo',
        projectId: 'p_pcas',
        dependsOn: ['t_model'],
        triggers: [],
        sources: [],
        history: [{ at: ago(0.3), by: 'user', summary: '创建' }],
        createdAt: ago(0.3),
        updatedAt: ago(0.3),
      },
      {
        id: 't_reply',
        title: '回复课程合作邮件',
        status: 'todo',
        projectId: 'p_yufolo',
        due: ahead(0, 17),
        dependsOn: [],
        triggers: [],
        sources: [
          {
            sourceId: 'src_email',
            label: '邮件：课堂实时字幕合作',
            excerpt: '想了解一下下学期能否在 3 门课上试用。',
            at: ago(2),
          },
        ],
        history: [{ at: ago(2), by: 'import', summary: '从邮件导入' }],
        createdAt: ago(2),
        updatedAt: ago(2),
      },
      {
        id: 't_archive',
        title: '把旧 PCAS 代码归档到 legacy 分支',
        status: 'done',
        projectId: 'p_pcas',
        dependsOn: [],
        triggers: [],
        sources: [],
        history: [{ at: ago(0.2), by: 'user', summary: '完成' }],
        createdAt: ago(0.4),
        updatedAt: ago(0.2),
      },
      {
        id: 't_ragtest',
        title: '给旧事件总线补 RAG 测试',
        notes: '定位改变，旧代码不再维护。',
        status: 'cancelled',
        projectId: 'p_pcas',
        dependsOn: [],
        triggers: [],
        sources: [],
        history: [{ at: ago(0.4), by: 'user', summary: '取消：旧代码不再维护' }],
        createdAt: ago(0.5),
        updatedAt: ago(0.4),
      },
    ],

    ideas: [
      {
        id: 'i_small_model',
        title: '用本地小模型做记忆提取',
        body: '把对话里的待办、事实和决定交给本地小模型提取，只有难例才调用云端模型。',
        status: 'shelved',
        projectId: 'p_model',
        shelvedReason: '云端 API 提取一次约 ¥0.03，本地推理当时没有可用的成本数据，无法判断是否划算。',
        conditions: [
          {
            id: 'c_cost',
            kind: 'info',
            description: '拿到本地小模型的实际推理成本，且单次提取低于云端的 1/5',
            met: false,
          },
          {
            id: 'c_review',
            kind: 'time',
            description: '11 月底统一复盘',
            dueAt: ahead(60, 9),
            met: false,
          },
        ],
        remindersOn: true,
        evolution: [
          { at: ago(24), by: 'user', summary: '在讨论小模型时提出' },
          { at: ago(23), by: 'user', summary: '补充：只有难例才走云端' },
          { at: ago(21), by: 'user', summary: '搁置：成本数据不足' },
        ],
        sources: [chat('讨论个人小模型', '要不要先让小模型做提取？', 24)],
        createdAt: ago(24),
        updatedAt: ago(21),
      },
      {
        id: 'i_weekly',
        title: '每月自动生成个人回顾',
        body: '汇总这个月完成的事、推进的 IDEA 和改变的决定，生成一页回顾。',
        status: 'awakened',
        projectId: 'p_pcas',
        shelvedReason: '先把核心记忆做出来。',
        conditions: [
          {
            id: 'c_month',
            kind: 'time',
            description: '每月 1 日前重新考虑',
            dueAt: ago(0.1),
            met: true,
            metAt: ago(0.1),
          },
        ],
        wake: {
          at: ago(0.1),
          reason: '你设定的重新考虑时间到了（每月 1 日前）。这个月新增了 9 条事项和 3 个决定，可以作为第一份回顾的素材。',
          conditionId: 'c_month',
        },
        remindersOn: true,
        evolution: [
          { at: ago(40), by: 'user', summary: '提出' },
          { at: ago(39), by: 'user', summary: '搁置：先做核心记忆' },
          { at: ago(0.1), by: 'system', summary: '到时间，重新唤醒' },
        ],
        sources: [],
        createdAt: ago(40),
        updatedAt: ago(0.1),
      },
      {
        id: 'i_context',
        title: 'IDEA 唤醒时附上当时的对话原文',
        body: '唤醒卡片里直接展开提出这个想法时的那段对话，免得回忆背景。',
        status: 'active',
        projectId: 'p_pcas',
        conditions: [],
        remindersOn: true,
        evolution: [{ at: ago(0.2), by: 'user', summary: '提出' }],
        sources: [chat('与 Claude 讨论 PCAS 重写')],
        createdAt: ago(0.2),
        updatedAt: ago(0.2),
      },
      {
        id: 'i_cards',
        title: '课堂转录自动生成复习卡片',
        body: 'Yufolo 课后根据转录生成复习卡片，接入学习模块的练习。',
        status: 'shelved',
        projectId: 'p_yufolo',
        shelvedReason: '先稳住核心转录体验。',
        conditions: [
          {
            id: 'c_wau',
            kind: 'event',
            description: '学习模块周活跃用户超过 500',
            met: false,
          },
        ],
        remindersOn: true,
        evolution: [
          { at: ago(30), by: 'user', summary: '提出' },
          { at: ago(30), by: 'user', summary: '搁置：先稳住核心体验' },
        ],
        sources: [],
        createdAt: ago(30),
        updatedAt: ago(30),
      },
      {
        id: 'i_store',
        title: 'PCAS 做成 D-App 应用商店',
        body: '旧定位下的想法：让第三方 D-App 通过事件总线接入。',
        status: 'dropped',
        projectId: 'p_pcas',
        shelvedReason: '定位改变，不再做平台。',
        conditions: [],
        remindersOn: false,
        evolution: [
          { at: ago(400), by: 'user', summary: '提出' },
          { at: ago(0.4), by: 'user', summary: '放弃：定位改变' },
        ],
        sources: [],
        createdAt: ago(400),
        updatedAt: ago(0.4),
      },
    ],

    memories: [
      {
        id: 'm_stack',
        kind: 'decision',
        text: 'PCAS 后端沿用 Go + PostgreSQL（pgvector），与 Yufolo 保持同一技术栈。',
        epistemic: 'confirmed',
        projectId: 'p_pcas',
        sources: [chat('与 Claude 讨论 PCAS 重写')],
        versions: [{ at: ago(0.3), by: 'user', text: 'PCAS 后端沿用 Go + PostgreSQL（pgvector），与 Yufolo 保持同一技术栈。' }],
        visibleTo: ['a_claude', 'a_chatgpt', 'a_codex'],
        exposure: 1,
        lastUsedAt: ago(0.2),
      },
      {
        id: 'm_legacy',
        kind: 'decision',
        text: '旧版 PCAS 代码不复用，只作为经验参考。',
        epistemic: 'confirmed',
        projectId: 'p_pcas',
        sources: [chat('与 Claude 讨论 PCAS 重写', '几乎我感觉全部都要重写')],
        versions: [{ at: ago(0.4), by: 'user', text: '旧版 PCAS 代码不复用，只作为经验参考。' }],
        visibleTo: ['a_claude', 'a_chatgpt', 'a_codex'],
        exposure: 0.9,
        lastUsedAt: ago(0.3),
      },
      {
        id: 'm_papez',
        kind: 'decision',
        text: '记忆系统参考 Papez 的设计思路自行重写，不复制它的代码。',
        epistemic: 'confirmed',
        projectId: 'p_pcas',
        sources: [chat('与 Claude 讨论 Papez')],
        versions: [
          { at: ago(0.35), by: 'ai', text: '原型阶段直接接入 Papez 作为记忆层。' },
          {
            at: ago(0.3),
            by: 'user',
            text: '记忆系统参考 Papez 的设计思路自行重写，不复制它的代码。',
            reason: '只让参考 Papez，我们要重写，不完全一样',
          },
        ],
        visibleTo: ['a_claude', 'a_chatgpt', 'a_codex'],
        exposure: 0.95,
        lastUsedAt: ago(0.3),
      },
      {
        id: 'm_lang',
        kind: 'preference',
        text: '界面和文档默认使用中文。',
        epistemic: 'confirmed',
        sources: [],
        versions: [{ at: ago(90), by: 'user', text: '界面和文档默认使用中文。' }],
        visibleTo: ['a_claude', 'a_chatgpt', 'a_codex'],
        exposure: 0.8,
        lastUsedAt: ago(1),
      },
      {
        id: 'm_localfirst',
        kind: 'preference',
        text: '倾向本地优先的部署方式。',
        epistemic: 'inferred',
        projectId: 'p_pcas',
        sources: [{ sourceId: 'src_import', label: '2025 年 PCAS 白皮书', excerpt: 'Absolute Data Sovereignty', at: ago(400) }],
        versions: [{ at: ago(0.3), by: 'ai', text: '倾向本地优先的部署方式。' }],
        visibleTo: ['a_claude'],
        exposure: 0.6,
        lastUsedAt: ago(0.3),
      },
      {
        id: 'm_yufolo',
        kind: 'fact',
        text: 'Yufolo 生产地址是 yufolo.com，后端 Go，数据库 PostgreSQL 16。',
        epistemic: 'confirmed',
        projectId: 'p_yufolo',
        sources: [{ sourceId: 'src_yufolo', label: 'Yufolo 部署文档', at: ago(5) }],
        versions: [{ at: ago(5), by: 'import', text: 'Yufolo 生产地址是 yufolo.com，后端 Go，数据库 PostgreSQL 16。' }],
        visibleTo: ['a_claude', 'a_chatgpt', 'a_codex'],
        exposure: 0.7,
        lastUsedAt: ago(2),
      },
      {
        id: 'm_cloudcost',
        kind: 'fact',
        text: '用云端 API 做一次记忆提取约 ¥0.03。',
        epistemic: 'confirmed',
        projectId: 'p_model',
        sources: [chat('讨论个人小模型', undefined, 22)],
        versions: [{ at: ago(22), by: 'user', text: '用云端 API 做一次记忆提取约 ¥0.03。' }],
        visibleTo: ['a_claude', 'a_chatgpt'],
        exposure: 0.4,
        lastUsedAt: ago(21),
      },
      {
        id: 'm_datamodel',
        kind: 'decision',
        text: '10 月内完成数据模型设计。',
        epistemic: 'planned',
        projectId: 'p_pcas',
        sources: [],
        versions: [{ at: ago(0.2), by: 'user', text: '10 月内完成数据模型设计。' }],
        visibleTo: ['a_claude', 'a_codex'],
        exposure: 0.9,
        lastUsedAt: ago(0.2),
      },
      {
        id: 'm_nodecay',
        kind: 'decision',
        text: '未完成事项不会因为长期不提而自动消失；衰减只影响曝光度。',
        epistemic: 'confirmed',
        projectId: 'p_pcas',
        sources: [{ sourceId: 'src_import', label: 'PCAS 需求简版 0.3', at: ago(0.5) }],
        versions: [{ at: ago(0.5), by: 'import', text: '未完成事项不会因为长期不提而自动消失；衰减只影响曝光度。' }],
        visibleTo: ['a_claude', 'a_chatgpt', 'a_codex'],
        exposure: 1,
        lastUsedAt: ago(0.1),
      },
      {
        id: 'm_scribe',
        kind: 'fact',
        text: '曾计划把 DreamScribe 做成笔记类 D-App。',
        epistemic: 'inferred',
        sources: [{ sourceId: 'src_import', label: '旧版 PCAS 文档', at: ago(420) }],
        versions: [{ at: ago(300), by: 'ai', text: '曾计划把 DreamScribe 做成笔记类 D-App。' }],
        visibleTo: [],
        exposure: 0.15,
        lastUsedAt: ago(300),
      },
    ],

    candidates: [
      {
        id: 'cd_trial',
        kind: 'task',
        text: '周五前把原型发给两位朋友试用',
        projectId: 'p_pcas',
        due: ahead(3, 18),
        confidence: 0.86,
        source: {
          sourceId: 'src_yufolo',
          label: 'Yufolo 转录：PCAS 周会',
          excerpt: '原型周五前应该能给两个朋友先试一下。',
          at: ago(0.5),
        },
        state: 'pending',
        createdAt: ago(0.5),
      },
      {
        id: 'cd_nowechat',
        kind: 'memory',
        memoryKind: 'decision',
        text: '第一版先不接微信和 QQ。',
        projectId: 'p_pcas',
        confidence: 0.72,
        source: {
          sourceId: 'src_yufolo',
          label: 'Yufolo 转录：PCAS 周会',
          excerpt: '微信那边先别碰了，第一版先把 Claude 和 ChatGPT 接好。',
          at: ago(0.5),
        },
        state: 'pending',
        createdAt: ago(0.5),
      },
      {
        id: 'cd_smreply',
        kind: 'task',
        text: '回复 Speechmatics 续期确认',
        projectId: 'p_yufolo',
        confidence: 0.64,
        source: {
          sourceId: 'src_email',
          label: '邮件：Startup Program renewal',
          excerpt: 'Please confirm your usage estimate for next quarter.',
          at: ago(0.2),
        },
        state: 'pending',
        createdAt: ago(0.2),
      },
      {
        id: 'cd_mdexport',
        kind: 'idea',
        text: '交接内容支持导出为 Markdown 文件',
        projectId: 'p_pcas',
        confidence: 0.58,
        source: {
          sourceId: 'src_claude',
          label: 'Claude 对话：交接格式',
          excerpt: '要是能直接存成 .md 丢给别的工具就好了。',
          at: ago(1),
        },
        state: 'pending',
        createdAt: ago(1),
      },
      {
        id: 'cd_temp',
        kind: 'memory',
        memoryKind: 'fact',
        text: 'OpenAI 新一代模型不接受自定义 temperature 参数。',
        confidence: 0.9,
        source: {
          sourceId: 'src_chatgpt',
          label: 'ChatGPT 导出：接口报错排查',
          at: ago(3),
        },
        state: 'pending',
        createdAt: ago(3),
      },
    ],

    sources: [
      { id: 'src_yufolo', name: 'Yufolo', method: '账号授权同步', status: 'connected', note: '转录、摘要、笔记和行动项', itemCount: 128, lastSyncAt: ago(0.5) },
      { id: 'src_claude', name: 'Claude', method: '官方数据导出（JSON）', status: 'manual', note: '手动上传导出文件', itemCount: 342, lastSyncAt: ago(1) },
      { id: 'src_chatgpt', name: 'ChatGPT', method: '官方数据导出（zip）', status: 'manual', note: '手动上传导出文件', itemCount: 517, lastSyncAt: ago(3) },
      { id: 'src_email', name: 'Email', method: 'IMAP', status: 'connected', note: '只读取收件箱和已发送', itemCount: 64, lastSyncAt: ago(0.2) },
      { id: 'src_wechat', name: '微信', method: '第三方导出工具', status: 'failed', note: '没有官方接口，导出方式待验证', itemCount: 0 },
      { id: 'src_qq', name: 'QQ', method: '待定', status: 'unverified', note: '没有官方接口，导出方式待验证', itemCount: 0 },
    ],

    jobs: [
      {
        id: 'j_claude',
        title: '提取 Claude 导出中的候选',
        trigger: 'manual',
        status: 'running',
        progress: 0.45,
        detail: '已处理 154 / 342 段对话',
        createdAt: ago(0.05),
      },
      {
        id: 'j_wake',
        title: '检查搁置 IDEA 的重新考虑条件',
        trigger: 'time',
        status: 'waiting',
        detail: '每天 21:00 运行；有新资料导入时也会运行',
        createdAt: ago(10),
        nextRunAt: ahead(0, 21),
      },
      {
        id: 'j_followup',
        title: '跟进提醒：Speechmatics 续期',
        trigger: 'event',
        status: 'queued',
        detail: '发出邮件 3 天后执行；执行前核对是否已收到回复',
        createdAt: ago(1),
        nextRunAt: ahead(2, 9),
      },
      {
        id: 'j_yufolo',
        title: '同步 Yufolo 会话',
        trigger: 'event',
        status: 'done',
        detail: '新增 3 段转录，提取出 2 条候选',
        createdAt: ago(0.5),
      },
      {
        id: 'j_wechat',
        title: '导入微信聊天记录',
        trigger: 'manual',
        status: 'failed',
        detail: '无法识别导出文件（数据库已加密）',
        recovery: '换用能导出 HTML 的工具，再重新导入',
        createdAt: ago(2),
      },
    ],

    agents: [
      { id: 'a_claude', name: 'Claude', channel: 'mcp', note: '通过 MCP 读写授权范围内的记忆', enabled: true, memoryKinds: ['fact', 'preference', 'decision'], includeInferred: false },
      { id: 'a_chatgpt', name: 'ChatGPT', channel: 'mcp', note: '通过 MCP 读取记忆', enabled: true, memoryKinds: ['fact', 'decision'], includeInferred: false },
      { id: 'a_codex', name: 'Codex', channel: 'api', note: '通过 Codex 订阅执行代码任务', enabled: true, memoryKinds: ['fact', 'decision'], includeInferred: false },
      { id: 'a_local', name: '本地模型', channel: 'api', note: 'Ollama，本机运行', enabled: false, memoryKinds: ['fact', 'preference', 'decision'], includeInferred: true },
      { id: 'a_manual', name: '手动交接', channel: 'manual', note: '复制内容粘贴给任意 AI，再把结果贴回来', enabled: true, memoryKinds: ['fact', 'preference', 'decision'], includeInferred: false },
    ],

    handoffs: [
      {
        id: 'h_lessons',
        title: '整理旧版 PCAS 的经验',
        agentId: 'a_claude',
        projectId: 'p_pcas',
        sections: {
          goal: '从旧版代码中整理出值得保留的经验，写成一页文档。',
          background: '旧版 PCAS 是事件总线 + 策略路由引擎，已归档到 legacy 分支。',
          progress: '已完成代码通读和问题清单。',
          decisions: '- 旧版 PCAS 代码不复用，只作为经验参考。',
          constraints: '只写经验，不写修复方案；控制在一页。',
          expectedOutput: '一份 Markdown 文档，按模型接入、存储检索、工程三部分组织。',
        },
        memoryIds: ['m_legacy'],
        status: 'returned',
        result: {
          at: ago(0.15),
          text: '## 模型接入\n- 新一代模型拒绝 max_tokens 和非默认 temperature\n## 存储与检索\n- 先检索再过滤会让召回率塌\n## 工程\n- 从第一天起强制格式化和 lint',
        },
        stale: false,
        createdAt: ago(0.25),
        updatedAt: ago(0.15),
      },
    ],

    samples: [
      {
        id: 's_papez',
        kind: 'correction',
        prompt: 'PCAS 的记忆系统要不要直接接入 Papez？',
        response: '只参考 Papez 的设计思路，自行重写，不复制代码。',
        origin: { label: '纠正：记忆 “Papez 的用法”', memoryId: 'm_papez' },
        version: 2,
        state: 'included',
        epistemic: 'confirmed',
        stale: false,
        createdAt: ago(0.3),
      },
      {
        id: 's_localfirst',
        kind: 'conversation',
        prompt: '用户倾向哪种部署方式？',
        response: '倾向本地优先。',
        origin: { label: '推断：记忆 “部署偏好”', memoryId: 'm_localfirst' },
        version: 1,
        state: 'excluded',
        epistemic: 'inferred',
        stale: false,
        createdAt: ago(0.3),
      },
    ],
  }
}
