run:
  modules-download-mode: vendor
  go: '1.23'

linters:
  disable-all: true  # 禁用所有默认 linter
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
  # typecheck is explicitly not enabled due to vendor issues

linters-settings:
  gofmt:
    simplify: true