run:
  # Timeout for analysis
  timeout: 5m
  
  # Include test files
  tests: true
  
  # Build tags
  build-tags:
    - netgo
  
  # Skip vendor directory
  skip-dirs:
    - vendor
  
  # Skip generated files
  skip-files:
    - ".*\\.pb\\.go$"

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - gosimple
    - unused
  
  disable:
    # Disable typecheck as it has issues with module resolution
    - typecheck
    # Disable other problematic linters
    - gosec
    - goconst
    - dupl

linters-settings:
  staticcheck:
    # Use Go 1.23 to match our go.mod
    go: "1.23"
    
  errcheck:
    # Check type assertions
    check-type-assertions: true
    # Check for ignored errors
    check-blank: true

issues:
  # Exclude some linters from running on test files
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - ineffassign