version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: pcas-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pcas
      - POSTGRES_PASSWORD=pcas_vector_db
      - POSTGRES_DB=pcas_vectors
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pcas -d pcas_vectors"]
      interval: 10s
      timeout: 5s
      retries: 5

  pcas:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: pcas-server
    ports:
      - "50051:50051"
    volumes:
      - .:/app
      - /app/vendor  # Prevent vendor directory from being overwritten
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-dummy-key}
      - PG_DSN=postgres://pcas:pcas_vector_db@postgres:5432/pcas_vectors?sslmode=disable
      - PCAS_ENV=development
      - GOFLAGS=-mod=readonly -buildvcs=false
    depends_on:
      postgres:
        condition: service_healthy
    command: ["air", "-c", ".air.toml"]

volumes:
  postgres_data:

networks:
  default:
    name: pcas-network