import { test, expect } from '@playwright/test'

test('persisted workspace, memory correction, source tracing and manual assistant', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  const suffix = Date.now().toString(36)
  const memoryText = `河边旧书店-${suffix}`
  await page.goto('/')
  await page.getByLabel('访问令牌').fill(process.env.PCAS_TEST_API_TOKEN ?? 'pcas-browser-check-secret-123456789012')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByPlaceholder('记点什么')).toBeVisible()
  await page.getByLabel('记点什么').fill(memoryText)
  await page.getByLabel('记点什么').press('Enter')
  await expect(page.getByText('记下了，后台会整理', { exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: /条需要你确认/ }).click()
  const candidate = page.locator('.item').filter({ hasText: memoryText })
  await candidate.getByLabel('这是').selectOption('memory')
  await candidate.getByRole('button', { name: '收下', exact: true }).click()
  await expect(candidate).toHaveCount(0)
  await page.keyboard.press('Escape')
  await page.goto('/library')
  await page.getByText(memoryText, { exact: true }).click()
  await expect(page.getByLabel('内容')).toHaveValue(memoryText)
  await page.getByLabel('内容').fill(`山边旧书店-${suffix}`)
  await page.getByRole('button', { name: '存为新版本' }).click()
  await expect(page.getByText('改好了，旧版本也留着', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /用户纠正/ }).click()
  await expect(page.locator('pre').filter({ hasText: `山边旧书店-${suffix}` })).toBeVisible()
  await page.goto('/')
  await expect(page.getByPlaceholder('记点什么')).toBeVisible()
  await page.keyboard.press('Control+k')
  await page.getByRole('dialog', { name: '搜索' }).getByLabel('搜索', { exact: true }).fill(`浏览器项目-${suffix}`)
  await page.getByRole('option', { name: `项目「浏览器项目-${suffix}」` }).click()
  await expect(page).toHaveURL(/\/t\/[0-9a-f-]+/)
  await page.getByLabel('交给谁').selectOption('manual')
  await page.getByLabel('交给副手').fill('请结合旧书店记忆提出一个计划')
  await page.getByRole('button', { name: '发送', exact: true }).click()
  await expect(page.getByLabel('贴回回答')).toBeVisible()
  await page.getByLabel('贴回回答').fill('先核对地址，再安排走访。')
  await page.getByRole('button', { name: '放回来', exact: true }).click()
  await expect(page.getByText('先核对地址，再安排走访。', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('先核对地址，再安排走访。', { exact: true })).toBeVisible()
  await page.goto('/settings')
  await expect(page.getByRole('heading', { name: 'ChatGPT 订阅', level: 2 })).toBeVisible()
  expect(errors).toEqual([])
})
