name: Build
on:
  push:
    branches: [ "main", "dev" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: bufbuild/buf-setup-action@v1
      
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      
      - name: Install protoc-gen-doc
        run: go install github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc@v1.5.1
      
      - name: Generate protobuf code
        run: make proto
      - run: make test

      # Docker 镜像（仅 push 到临时 tag SHA）
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/soaringjerry/pcas:${{ github.sha }}