name: Build
on:
  push:
    branches: [ "main", "dev" ]

permissions:
  contents: read
  packages: write

jobs:
  pre-build:
    uses: ./.github/workflows/generate-code.yml

  build:
    runs-on: ubuntu-latest
    needs: pre-build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: make test

      # Docker 镜像（仅 push 到临时 tag SHA）
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/soaringjerry/pcas:${{ github.sha }}