name: CI
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: bufbuild/buf-setup-action@v1
      
      - name: Generate protobuf code
        run: make proto
        continue-on-error: true # Temporarily allow failure due to buf version issues
        
      - name: Check for breaking changes in protobuf
        run: buf breaking --against '.git#branch=main'
        continue-on-error: true # Temporarily allow failure

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          
      - name: Sync vendor directory
        run: go mod vendor
          
      - name: Run go vet
        run: go vet ./...
        
      - name: Lint Go files
        run: make lint
        continue-on-error: true # Temporarily allow failure due to typecheck issues in vendor mode
        
      - name: Run tests
        run: make test