name: CI
on:
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: bufbuild/buf-setup-action@v1
      - run: make proto  # 生成代码并验证和 repo 中一致
      - run: buf breaking --against '.git#branch=main'

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go vet ./...
      - run: make lint        # golangci-lint
      - run: make test        # go test ./...